"""create initial tables

Revision ID: 43ce4263abf0
Revises: 
Create Date: 2026-06-24 17:51:20.985286
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ce4263abf0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asteroids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nasa_id', sa.String(), nullable=False),
    sa.Column('close_approach_date', sa.DateTime(), nullable=False),
    sa.Column('miss_distance_km', sa.Float(), nullable=False),
    sa.Column('relative_velocity_kmh', sa.Float(), nullable=False),
    sa.Column('is_potentially_hazardous', sa.Boolean(), nullable=False),
    sa.Column('absolute_magnitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nasa_id')
    )
    op.create_table('coronal_mass_ejections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cme_id', sa.String(), nullable=False),
    sa.Column('cme_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('source_location', sa.String(), nullable=True),
    sa.Column('active_region_num', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('instruments', sa.String(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('half_angle', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cme_id')
    )
    op.create_table('flares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flare_id', sa.String(), nullable=False),
    sa.Column('flare_class', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('peak_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('source_location', sa.String(), nullable=True),
    sa.Column('active_region_num', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flare_id')
    )
    op.create_table('geomagnetic_storms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gst_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('kp_index_max', sa.Float(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gst_id')
    )
    op.create_table('interplanetary_shocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ips_id', sa.String(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('instruments', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ips_id')
    )
    op.create_table('launches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('launch_id', sa.String(), nullable=False),
    sa.Column('launch_site', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('launch_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rocket_name', sa.String(), nullable=False),
    sa.Column('rocket_type', sa.String(), nullable=False),
    sa.Column('mission_name', sa.String(), nullable=True),
    sa.Column('mission_description', sa.String(), nullable=True),
    sa.Column('is_crewed', sa.Boolean(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('launch_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('launches')
    op.drop_table('interplanetary_shocks')
    op.drop_table('geomagnetic_storms')
    op.drop_table('flares')
    op.drop_table('coronal_mass_ejections')
    op.drop_table('asteroids')
    # ### end Alembic commands ###
